/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface VideoJobs {
  attempt: Generated<number>;
  createdAt: Generated<Timestamp>;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  maxAttempts: Generated<number>;
  payload: Generated<Json>;
  runAt: Generated<Timestamp>;
  startedAt: Timestamp | null;
  state: Generated<string>;
  updatedAt: Generated<Timestamp>;
  videoId: string;
}

export interface Videos {
  createdAt: Generated<Timestamp>;
  error: Json | null;
  externalId: string;
  id: Generated<string>;
  meta: Json | null;
  source: string;
  status: Generated<string>;
  statusMessage: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  videoJobs: VideoJobs;
  videos: Videos;
}
