/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface VideoArticles {
  article: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp>;
  videoId: string;
}

export interface VideoCaptions {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  plainText: string;
  updatedAt: Generated<Timestamp>;
  videoId: string;
  vttText: string;
}

export interface VideoInfos {
  categories: Generated<string[]>;
  channelId: string | null;
  channelTitle: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  duration: number | null;
  fulltitle: string | null;
  id: Generated<string>;
  language: string | null;
  tags: Generated<string[]>;
  updatedAt: Generated<Timestamp>;
  videoId: string;
}

export interface Videos {
  createdAt: Generated<Timestamp>;
  error: Json | null;
  externalId: string;
  id: Generated<string>;
  source: string;
  status: Generated<string>;
  statusMessage: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  videoArticles: VideoArticles;
  videoCaptions: VideoCaptions;
  videoInfos: VideoInfos;
  videos: Videos;
}
