name: tubebook-dev

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      # for local development
      - '127.0.0.1:${API_PORT}:3000'
    volumes:
      - ./:/app
      # Exclude to avoid conflicts
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env
    restart: unless-stopped
    command: "pnpm --filter ./apps/api dev"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    depends_on:
      - api
    ports:
      # for local development
      - '127.0.0.1:${WEB_PORT}:80'
    volumes:
      - ./:/app
      # Exclude to avoid conflicts
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "500"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
    env_file:
      - .env
    restart: unless-stopped
    command: "pnpm --filter ./apps/web dev"

  postgres:
    image: 'pgvector/pgvector:pg18-trixie'
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    user: postgres

volumes:
  postgres-data:
