name: tubebook-dev

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      schemas:
        condition: service_started
    volumes:
      - ./:/app
      # Exclude to avoid conflicts
      - /app/node_modules
      - /app/apps/api/node_modules
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${API_PORT}:3000'
    networks:
      - database_network
      - redis_network
      - web_network
    command: "pnpm --filter ./apps/api dev"
    restart: unless-stopped

  mastra:
    build:
      context: .
      dockerfile: ./apps/mastra/Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      # Exclude to avoid conflicts
      - /app/node_modules
      - /app/apps/mastra/node_modules
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${MASTRA_PORT}:4111'
    networks:
      - database_network
    command: "pnpm --filter ./apps/mastra dev"
    restart: unless-stopped

  postgres:
    image: 'pgvector/pgvector:pg18-trixie'
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    networks:
      - database_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432" ]
      interval: 5s
      timeout: 3s
      retries: 20
    user: postgres

  redis:
    image: redis:8-alpine
    volumes:
      - redis-data:/data
    ports:
      # for local development
      - '127.0.0.1:${REDIS_PORT}:6379'
    networks:
      - redis_network
    command: >
      redis-server --appendonly yes --appendfsync everysec --maxmemory 512mb --maxmemory-policy noeviction
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20

  schemas:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
      args:
        FOLDER: packages/schemas
    volumes:
      - ./:/app
      # Exclude to avoid conflicts
      - /app/node_modules
      - /app/packages/schemas/node_modules
    environment:
      # for local development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
    command: "pnpm --filter @tubebook/schemas dev"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    depends_on:
      api:
        condition: service_started
      schemas:
        condition: service_started
    volumes:
      - ./:/app
      # Exclude to avoid conflicts
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      # for local development
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "500"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${WEB_PORT}:80'
    networks:
      - web_network
    command: "pnpm --filter ./apps/web dev"
    restart: unless-stopped

networks:
  database_network:
    driver: bridge
  redis_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
