packages:
  - apps/**
  - libs/**
  - packages/**

ignoredBuiltDependencies:
  - ytdlp-nodejs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - esbuild
  - msgpackr-extract
  - msw
  - protobufjs
  - sharp
  - unrs-resolver
